//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchant()
        {
            this.Terminal = new HashSet<Terminal>();
        }
    
        public decimal MerchanID { get; set; }
        public Nullable<decimal> CustomerID { get; set; }

        [Required (ErrorMessage ="Bu Alaný Boþ Býrakamazsýn")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karakterlik Ýsim Girin")]
        public string MerchantName { get; set; }
        public string Adress { get; set; }
        public string Telephone { get; set; }
        public string VergiNo { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Terminal> Terminal { get; set; }
    }
}
