//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public decimal SaleID { get; set; }
        public Nullable<decimal> TerminalID { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Curreny { get; set; }
        public string TransactionType { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
